name: Deploy

env:
  DOCKER_IMAGE: ${{ github.repository }}/ruby_google_scraper
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_USERNAME: ${{ github.repository_owner }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP: ruby-google-scraper-staging

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nimblehq/branch-tag-action@v1

      - name: Docker login to Github package registry
        run: "echo $DOCKER_TOKEN | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin"

      - name: Docker build
        run: |
          bin/docker-prepare
          docker-compose build
          docker-compose push web

      - name: Heroku login
        run: heroku container:login
  
      - name: Heroku release
        run: |
          heroku container:push --arg DOCKER_REGISTRY=$DOCKER_REGISTRY,DOCKER_IMAGE=$DOCKER_IMAGE,BRANCH_TAG=$BRANCH_TAG --recursive
          heroku container:release web worker