name: CI

env:
  COMPOSE_FILE: docker-compose.test.yml
  CR_PAT: ${{ secrets.CR_PAT }} # Github container registry personal access token
  CR_USERNAME: ${{ github.repository_owner }} # Github container registry username
  DOCKER_IMAGE: ${{ github.repository }}/ruby_google_scraper
  REGISTRY_HOST: docker.pkg.github.com

on: push

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nimblehq/branch-tag-action@v1

      - name: Docker login to Github Container registry
        run: "echo $CR_PAT | docker login ghcr.io -u $CR_USERNAME --password-stdin"

      - name: Docker pull
        if: env.BRANCH_TAG != 'master' && env.BRANCH_TAG != 'development'
        run: | 
          echo Pulling built image for the branch
          docker-compose pull test

      - name: Docker build
        run: |
          bin/docker-prepare
          docker-compose build
          docker-compose push test