name: CI

env:
  COMPOSE_FILE: docker-compose.test.yml
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.repository_owner }}
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nimblehq/branch-tag-action@v1

      - name: Docker login to Github package registry
        run: "echo $DOCKER_TOKEN | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin"

      - name: Docker pull
        if: env.BRANCH_TAG != 'master' && env.BRANCH_TAG != 'development'
        run: | 
          echo Pulling built image for the branch
          docker-compose pull test || true

      - name: Docker build
        run: |
          bin/docker-prepare
          docker-compose build
          docker-compose push test

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: nimblehq/branch-tag-action@v1

      - name: Docker login to Github package registry
        run: "echo $DOCKER_TOKEN | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin"

      - name: Docker pull
        run: docker-compose pull
      
      - name: Linters
        run: docker-compose run test yarn lint

      - name: Unit tests
        run: docker-compose run test bundle exec rspec --exclude-pattern "spec/systems/**/*_spec.rb" --profile

      - name: System tests
        run: docker-compose run test bundle exec rspec spec/systems --profile